name: Unit Test

on:
  pull_request:
    paths:
      - 'vqpy/**'
      - 'test/**'
      - 'setup.py'
      - 'pyproject.toml'
      - '.github/workflows/**'
  push:

jobs:
  flake8:
    name: flake8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: flake8 Lint
        uses: py-actions/flake8@v2

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Dependencies
        shell: bash
        run: |
          pip install torch torchvision numpy==1.23.5 cython
          pip install pytest

      - name: install vqpy
        shell: bash
        run: |
          pip install 'vqpy @ git+https://github.com/vqpy/vqpy.git'

      - name: unit tests
        shell: bash
        run: |
          pytest test/unit_tests

      - name: prepare files for e2e tests
        uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: s3://vqpy/tests/
          destination: ./
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-west-2
          flags: --recursive

      - name: e2e tests
        shell: bash
        run: |
          pytest test/e2e_tests